from __future__ import annotations

from dataclasses import asdict, dataclass, field, replace


@dataclass(frozen=True, slots=True)
class ProviderDescriptor:
    id: str
    display_name: str
    environment_variable: str | None
    default_base_url: str | None
    authentication_type: str
    api_style: str
    adapter: str
    models_endpoint: str | None
    chat_endpoint: str | None
    responses_endpoint: str | None
    embeddings_support: bool
    vision_support: bool
    reasoning_support: bool
    tool_calling_support: bool
    streaming_support: bool
    local_or_cloud: str
    pricing_model: str
    integration_status: str = "METADATA_ONLY"
    reason: str = "No adapter classification has been recorded."
    required_adapter: str | None = None
    models_discovery_supported: bool = False
    chat_supported: bool = False
    pricing_metadata: dict[str, object] = field(default_factory=dict)
    quota_metadata: dict[str, object] = field(default_factory=dict)
    documentation_url: str | None = None

    def public_view(self) -> dict[str, object]:
        return asdict(self)


def provider_catalog() -> dict[str, ProviderDescriptor]:
    descriptors = [
        _provider(
            "openai",
            "OpenAI",
            "OPENAI_API_KEY",
            "https://api.openai.com/v1",
            "responses",
            True,
            True,
            True,
            True,
            True,
            "cloud",
            "paid",
        ),
        _provider(
            "openai_compatible",
            "OpenAI-compatible",
            None,
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "custom",
            "unknown",
        ),
        _provider(
            "ollama_local",
            "Ollama local",
            None,
            "http://127.0.0.1:11434/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "local",
            "free",
        ),
        _provider(
            "lm_studio",
            "LM Studio",
            None,
            "http://127.0.0.1:1234/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "local",
            "free",
        ),
        _provider(
            "vllm",
            "vLLM",
            None,
            "http://127.0.0.1:8000/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "local",
            "free",
        ),
        _provider(
            "llama_cpp",
            "llama.cpp",
            None,
            "http://127.0.0.1:8080/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "local",
            "free",
        ),
        _provider(
            "nvidia_nim",
            "NVIDIA NIM",
            "NVIDIA_API_KEY",
            "https://integrate.api.nvidia.com/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "modelscope",
            "ModelScope",
            "MODELSCOPE_API_KEY",
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _native(
            "cloudflare_workers_ai",
            "Cloudflare Workers AI",
            "CLOUDFLARE_API_KEY",
            "cloudflare",
            "cloud",
            "mixed",
            vision=True,
            streaming=True,
        ),
        _provider(
            "gemini",
            "Google Gemini",
            "GEMINI_API_KEY",
            "https://generativelanguage.googleapis.com/v1beta/openai",
            "chat_completions",
            False,
            True,
            True,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _github_models(),
        _provider(
            "groq",
            "Groq",
            "GROQ_API_KEY",
            "https://api.groq.com/openai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "ovhcloud",
            "OVHcloud AI Endpoints",
            "OVHCLOUD_API_KEY",
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _native("llm7", "LLM7.io", "LLM7_API_KEY", "metadata", "cloud", "unknown"),
        _provider(
            "mistral",
            "Mistral AI",
            "MISTRAL_API_KEY",
            "https://api.mistral.ai/v1",
            "chat_completions",
            True,
            True,
            True,
            True,
            True,
            "cloud",
            "paid",
        ),
        _native("opencode_zen", "OpenCode Zen", "OPENCODE_API_KEY", "metadata", "cloud", "unknown"),
        _provider(
            "cerebras",
            "Cerebras",
            "CEREBRAS_API_KEY",
            "https://api.cerebras.ai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _native(
            "cohere",
            "Cohere",
            "COHERE_API_KEY",
            "cohere",
            "cloud",
            "mixed",
            embeddings=True,
            vision=True,
            tools=True,
            streaming=True,
        ),
        _provider(
            "ollama_cloud",
            "Ollama Cloud",
            "OLLAMA_API_KEY",
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _native("agnes_ai", "Agnes AI", "AGNES_API_KEY", "metadata", "cloud", "unknown"),
        _provider(
            "aion_labs",
            "Aion Labs",
            "AION_API_KEY",
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "unknown",
        ),
        _provider(
            "huggingface",
            "Hugging Face Inference Providers",
            "HUGGINGFACE_API_KEY",
            "https://router.huggingface.co/v1",
            "responses",
            True,
            True,
            True,
            True,
            True,
            "cloud",
            "credit_based",
        ),
        _native("kilo_code", "Kilo Code", "KILO_API_KEY", "metadata", "cloud", "unknown"),
        _provider(
            "alibaba_model_studio",
            "Alibaba Cloud Model Studio",
            "DASHSCOPE_API_KEY",
            "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "z_ai",
            "Z AI",
            "ZAI_API_KEY",
            "https://open.bigmodel.cn/api/paas/v4",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "sambanova",
            "SambaNova Cloud",
            "SAMBANOVA_API_KEY",
            "https://api.sambanova.ai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "siliconflow",
            "SiliconFlow",
            "SILICONFLOW_API_KEY",
            "https://api.siliconflow.cn/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "xai",
            "xAI",
            "XAI_API_KEY",
            "https://api.x.ai/v1",
            "chat_completions",
            False,
            True,
            True,
            True,
            True,
            "cloud",
            "paid",
        ),
        _provider(
            "chutes",
            "Chutes.ai",
            "CHUTES_API_KEY",
            "https://llm.chutes.ai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "glhf",
            "Glhf.chat",
            "GLHF_API_KEY",
            "https://glhf.chat/api/openai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "ai21",
            "AI21 Labs",
            "AI21_API_KEY",
            "https://api.ai21.com/studio/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "paid",
        ),
        _provider(
            "deepseek",
            "DeepSeek",
            "DEEPSEEK_API_KEY",
            "https://api.deepseek.com/v1",
            "chat_completions",
            False,
            False,
            True,
            True,
            True,
            "cloud",
            "paid",
        ),
        _provider(
            "nscale",
            "Nscale",
            "NSCALE_API_KEY",
            None,
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "nebius",
            "Nebius AI Studio",
            "NEBIUS_API_KEY",
            "https://api.studio.nebius.ai/v1",
            "chat_completions",
            False,
            False,
            False,
            True,
            True,
            "cloud",
            "mixed",
        ),
        _provider(
            "openrouter",
            "OpenRouter",
            "OPENROUTER_API_KEY",
            "https://openrouter.ai/api/v1",
            "chat_completions",
            False,
            True,
            True,
            True,
            True,
            "cloud",
            "mixed",
        ),
    ]
    return {descriptor.id: _classify(descriptor) for descriptor in descriptors}


def _provider(
    provider_id: str,
    display_name: str,
    environment_variable: str | None,
    base_url: str | None,
    api_style: str,
    embeddings: bool,
    vision: bool,
    reasoning: bool,
    tools: bool,
    streaming: bool,
    location: str,
    pricing: str,
) -> ProviderDescriptor:
    return ProviderDescriptor(
        id=provider_id,
        display_name=display_name,
        environment_variable=environment_variable,
        default_base_url=base_url,
        authentication_type="bearer" if environment_variable else "none_or_bearer",
        api_style=api_style,
        adapter="openai_compatible",
        models_endpoint="/models",
        chat_endpoint="/chat/completions",
        responses_endpoint="/responses" if api_style == "responses" else None,
        embeddings_support=embeddings,
        vision_support=vision,
        reasoning_support=reasoning,
        tool_calling_support=tools,
        streaming_support=streaming,
        local_or_cloud=location,
        pricing_model=pricing,
    )


def _native(
    provider_id: str,
    display_name: str,
    environment_variable: str,
    adapter: str,
    location: str,
    pricing: str,
    *,
    embeddings: bool = False,
    vision: bool = False,
    reasoning: bool = False,
    tools: bool = False,
    streaming: bool = False,
) -> ProviderDescriptor:
    return ProviderDescriptor(
        id=provider_id,
        display_name=display_name,
        environment_variable=environment_variable,
        default_base_url=None,
        authentication_type="bearer",
        api_style="native",
        adapter=adapter,
        models_endpoint=None,
        chat_endpoint=None,
        responses_endpoint=None,
        embeddings_support=embeddings,
        vision_support=vision,
        reasoning_support=reasoning,
        tool_calling_support=tools,
        streaming_support=streaming,
        local_or_cloud=location,
        pricing_model=pricing,
    )


def _github_models() -> ProviderDescriptor:
    return ProviderDescriptor(
        id="github_models",
        display_name="GitHub Models",
        environment_variable="GITHUB_TOKEN",
        default_base_url="https://models.github.ai",
        authentication_type="bearer",
        api_style="github_models",
        adapter="github_models",
        models_endpoint="/catalog/models",
        chat_endpoint="/inference/chat/completions",
        responses_endpoint=None,
        embeddings_support=False,
        vision_support=True,
        reasoning_support=False,
        tool_calling_support=True,
        streaming_support=True,
        local_or_cloud="cloud",
        pricing_model="mixed",
    )


def _classify(descriptor: ProviderDescriptor) -> ProviderDescriptor:
    if descriptor.id in {"openai", "huggingface"}:
        return replace(
            descriptor,
            integration_status="EXECUTABLE",
            reason="The registry has a tested OpenAI Responses transport shape for this provider.",
            models_discovery_supported=True,
            chat_supported=True,
            documentation_url=_DOCUMENTATION.get(descriptor.id),
        )
    if descriptor.id in _OPENAI_COMPATIBLE:
        return replace(
            descriptor,
            integration_status="OPENAI_COMPATIBLE",
            reason=(
                "Uses the reusable OpenAI Chat Completions adapter; credentials and endpoint "
                "remain operator-configured."
            ),
            models_discovery_supported=True,
            chat_supported=True,
            documentation_url=_DOCUMENTATION.get(descriptor.id),
        )
    if descriptor.local_or_cloud == "local" or descriptor.id == "openai_compatible":
        return replace(
            descriptor,
            integration_status="LOCAL",
            reason="Requires a discovered or manually configured local OpenAI-compatible endpoint.",
            models_discovery_supported=True,
            chat_supported=True,
            documentation_url=_DOCUMENTATION.get(descriptor.id),
        )
    if descriptor.adapter not in {"metadata", "openai_compatible"}:
        return replace(
            descriptor,
            integration_status="NATIVE_ADAPTER",
            reason=(
                "Provider has a distinct management or inference API that needs a dedicated "
                "adapter."
            ),
            required_adapter=descriptor.adapter,
            documentation_url=_DOCUMENTATION.get(descriptor.id),
        )
    return replace(
        descriptor,
        adapter="metadata",
        models_endpoint=None,
        chat_endpoint=None,
        responses_endpoint=None,
        integration_status="METADATA_ONLY",
        reason="No verified reusable adapter is included for this provider yet.",
        required_adapter="native_or_verified_openai_compatible",
        documentation_url=_DOCUMENTATION.get(descriptor.id),
    )


_OPENAI_COMPATIBLE = {
    "nvidia_nim",
    "gemini",
    "groq",
    "mistral",
    "cerebras",
    "openrouter",
}


_DOCUMENTATION = {
    "nvidia_nim": "https://build.nvidia.com/settings/api-keys",
    "modelscope": "https://modelscope.cn/my/myaccesstoken",
    "cloudflare_workers_ai": "https://developers.cloudflare.com/workers-ai/get-started/rest-api/",
    "gemini": "https://ai.google.dev/gemini-api/docs/openai",
    "github_models": "https://docs.github.com/en/rest/models/catalog",
    "groq": "https://console.groq.com/keys",
    "ovhcloud": "https://docs.ovhcloud.com/en/guides/public-cloud/ai-machine-learning/ai-endpoints-getting-started",
    "llm7": "https://llm7.io/",
    "mistral": "https://console.mistral.ai/api-keys",
    "opencode_zen": "https://opencode.ai/docs/pt-br/zen/",
    "cerebras": "https://cloud.cerebras.ai/",
    "cohere": "https://docs.cohere.com/",
    "ollama_cloud": "https://ollama.com/settings/keys",
    "agnes_ai": "https://platform.agnes-ai.com/settings/apiKeys",
    "aion_labs": "https://www.aionlabs.ai/",
    "huggingface": "https://huggingface.co/docs/inference-providers/guides/responses-api",
    "kilo_code": "https://kilo.ai/",
    "alibaba_model_studio": "https://bailian.console.aliyun.com/",
    "z_ai": "https://z.ai/",
    "sambanova": "https://cloud.sambanova.ai/",
    "siliconflow": "https://siliconflow.cn/",
    "xai": "https://console.x.ai/",
    "chutes": "https://chutes.ai/",
    "glhf": "https://glhf.chat/",
    "ai21": "https://studio.ai21.com/",
    "deepseek": "https://platform.deepseek.com/api_keys",
    "nscale": "https://www.nscale.com/",
    "nebius": "https://studio.nebius.ai/",
    "openai": "https://platform.openai.com/docs/api-reference/models",
    "openrouter": "https://openrouter.ai/docs",
    "ollama_local": "https://docs.ollama.com/api/openai-compatibility",
    "lm_studio": "https://lmstudio.ai/docs/developer/openai-compat",
    "vllm": "https://docs.vllm.ai/en/latest/serving/openai_compatible_server/",
    "llama_cpp": "https://github.com/ggml-org/llama.cpp/tree/master/examples/server",
}
